const http=require('http'),fs=require('fs'),path=require('path'),{kundali,panchang}=require('./lib/vedic');
const PORT=Number(process.env.PORT||8765),HOST=process.env.HOST||'127.0.0.1',API_KEY=process.env.GEMINI_API_KEY||'',MODEL=process.env.GEMINI_MODEL||'gemini-2.5-flash';
const SYSTEM='You are a sophisticated modern Vedic astrologer with 30 years of experience. Respond in clear, elegant English. Give detailed, personalized, spiritually insightful readings. Always cover multiple life areas. Use relevant emojis. Be warm, accurate, and empowering. Never give generic advice — make every reading feel personal and cosmic. Clearly disclose when an exact astronomical calculation cannot be made from the supplied data.';
const buckets=new Map(),WINDOW_MS=60000,MAX_REQUESTS=Number(process.env.RATE_LIMIT||12);
function securityHeaders(type='application/json; charset=utf-8'){return {'Content-Type':type,'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; base-uri 'none'; form-action 'self'",'Cache-Control':type.startsWith('text/html')?'no-cache':'no-store'}}
function send(res,status,data){res.writeHead(status,securityHeaders());res.end(JSON.stringify(data))}
function limited(ip){const now=Date.now(),b=buckets.get(ip);if(!b||now-b.start>WINDOW_MS){buckets.set(ip,{start:now,count:1});return false}return ++b.count>MAX_REQUESTS}
function readBody(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>20000){reject(new Error('Request too large'));req.destroy()}});req.on('end',()=>resolve(s));req.on('error',reject)})}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);
if(req.method==='GET'&&url.pathname==='/health')return send(res,200,{ok:true,aiConfigured:Boolean(API_KEY),version:'1.0.0'});
if(req.method==='GET'&&url.pathname==='/api/panchang')return send(res,200,panchang({date:url.searchParams.get('date')||new Date().toISOString(),lat:+url.searchParams.get('lat'),lon:+url.searchParams.get('lon')}));
if(req.method==='GET'&&url.pathname==='/api/geocode'){const q=String(url.searchParams.get('q')||'').trim();if(q.length<3)return send(res,400,{error:'Enter at least 3 characters'});try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&q=${encodeURIComponent(q)}`,{headers:{'User-Agent':'JyotishDarpan/1.0'}}),d=await r.json();return send(res,200,d.map(x=>({name:x.display_name,lat:+x.lat,lon:+x.lon})))}catch{return send(res,502,{error:'Place search unavailable'})}}
if(req.method==='POST'&&url.pathname==='/api/kundali'){try{const b=JSON.parse(await readBody(req));if(!/^\d{4}-\d{2}-\d{2}$/.test(b.date)||!Number.isFinite(+b.lat)||!Number.isFinite(+b.lon))return send(res,400,{error:'Valid date, latitude and longitude required'});return send(res,200,kundali(b))}catch{return send(res,400,{error:'Unable to calculate chart'})}}
if(req.method==='POST'&&url.pathname==='/api/reading'){if(limited(req.socket.remoteAddress||'unknown'))return send(res,429,{error:'Too many readings. Please wait one minute.'});if(!API_KEY)return send(res,503,{error:'AI service is not configured. Set GEMINI_API_KEY on the server.'});try{const parsed=JSON.parse(await readBody(req)),prompt=typeof parsed.prompt==='string'?parsed.prompt.trim():'';if(prompt.length<5||prompt.length>6000)return send(res,400,{error:'Please provide a valid reading request.'});const endpoint=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(MODEL)}:generateContent`,upstream=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':API_KEY},body:JSON.stringify({systemInstruction:{parts:[{text:SYSTEM}]},contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{maxOutputTokens:1000,temperature:0.8}})}),data=await upstream.json();if(!upstream.ok){console.error('Gemini error',upstream.status,data?.error?.status);return send(res,502,{error:'AI reading is temporarily unavailable.'})}const text=(data.candidates?.[0]?.content?.parts||[]).map(x=>x.text||'').join('\n').trim();if(!text)return send(res,502,{error:'AI returned no reading. Please try again.'});return send(res,200,{text})}catch(err){console.error(err.message);return send(res,400,{error:'Unable to process this request.'})}}
if(req.method!=='GET'&&req.method!=='HEAD')return send(res,405,{error:'Method not allowed'});const requested=url.pathname==='/'?'index.html':url.pathname.slice(1),types={'index.html':'text/html; charset=utf-8','enhancements.js':'text/javascript; charset=utf-8','sw.js':'text/javascript; charset=utf-8','manifest.webmanifest':'application/manifest+json'},file=path.resolve(__dirname,requested),name=path.basename(file);if(!file.startsWith(path.resolve(__dirname))||!types[name])return send(res,404,{error:'Not found'});fs.readFile(file,(err,data)=>{if(err)return send(res,404,{error:'Not found'});res.writeHead(200,securityHeaders(types[name]));res.end(req.method==='HEAD'?'':data)})});
server.listen(PORT,HOST,()=>console.log(`Jyotish Darpan running on http://${HOST}:${PORT}`));
