const Astronomy=require('astronomy-engine'),tzlookup=require('tz-lookup');
const SIGNS=['Mesh','Vrishabh','Mithun','Kark','Singh','Kanya','Tula','Vrishchik','Dhanu','Makar','Kumbh','Meen'];
const NAK=['Ashwini','Bharani','Krittika','Rohini','Mrigashira','Ardra','Punarvasu','Pushya','Ashlesha','Magha','Purva Phalguni','Uttara Phalguni','Hasta','Chitra','Swati','Vishakha','Anuradha','Jyeshtha','Mula','Purva Ashadha','Uttara Ashadha','Shravana','Dhanishta','Shatabhisha','Purva Bhadrapada','Uttara Bhadrapada','Revati'];
const norm=x=>(x%360+360)%360;
function ayanamsa(date){return 23.8531+0.013968*(date.getUTCFullYear()+(date.getUTCMonth()+0.5)/12-2000)}
function tropical(body,date){if(body==='Sun')return Astronomy.SunPosition(date).elon;if(body==='Moon')return Astronomy.EclipticGeoMoon(date).lon;return Astronomy.Ecliptic(Astronomy.GeoVector(Astronomy.Body[body],date,true)).elon}
function sidereal(body,date){return norm(tropical(body,date)-ayanamsa(date))}
function detail(body,lon){return {body,longitude:+lon.toFixed(4),sign:SIGNS[Math.floor(lon/30)],degree:+(lon%30).toFixed(2),house:null}}
function chart(date){const names=['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn'],planets=names.map(n=>detail(n,sidereal(n,date))),moon=planets[1].longitude,node=norm(125.04452-0.0529538083*((date-Date.UTC(2000,0,1,12))/86400000)-ayanamsa(date));planets.push(detail('Rahu',node),detail('Ketu',norm(node+180)));return {ayanamsa:'Lahiri (approximation)',ayanamsaDegrees:+ayanamsa(date).toFixed(4),planets,moonSign:SIGNS[Math.floor(moon/30)],nakshatra:NAK[Math.floor(moon/(360/27))],nakshatraPada:Math.floor((moon%(360/27))/(360/108))+1}}
function ascendant(date,lat,lon){const eps=23.439291*Math.PI/180,theta=norm(Astronomy.SiderealTime(date)*15+lon)*Math.PI/180,phi=lat*Math.PI/180;return norm(Math.atan2(-Math.cos(theta),Math.sin(theta)*Math.cos(eps)+Math.tan(phi)*Math.sin(eps))*180/Math.PI-ayanamsa(date))}
function localDate(input){if(input.offset)return new Date(`${input.date}T${input.time||'12:00'}:00${input.offset}`);const zone=tzlookup(+input.lat,+input.lon),[y,m,d]=input.date.split('-').map(Number),[hh,mm]=(input.time||'12:00').split(':').map(Number),guess=new Date(Date.UTC(y,m-1,d,hh,mm)),parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(guess).filter(x=>x.type!=='literal').map(x=>[x.type,+x.value])),shown=Date.UTC(parts.year,parts.month-1,parts.day,parts.hour,parts.minute),wanted=Date.UTC(y,m-1,d,hh,mm);return new Date(guess.getTime()-(shown-wanted))}
function kundali(input){const date=localDate(input),base=chart(date),lagna=ascendant(date,+input.lat,+input.lon);base.timezone=tzlookup(+input.lat,+input.lon);base.utcTime=date.toISOString();base.lagna={longitude:+lagna.toFixed(4),sign:SIGNS[Math.floor(lagna/30)],degree:+(lagna%30).toFixed(2)};base.planets.forEach(p=>p.house=(Math.floor(norm(p.longitude-lagna)/30)+1));const mars=base.planets.find(p=>p.body==='Mars'),moon=base.planets.find(p=>p.body==='Moon'),venus=base.planets.find(p=>p.body==='Venus'),doshaHouses=[1,2,4,7,8,12],from=x=>Math.floor(norm(mars.longitude-x)/30)+1;const checks={lagna:doshaHouses.includes(mars.house),moon:doshaHouses.includes(from(moon.longitude)),venus:doshaHouses.includes(from(venus.longitude))},hits=Object.values(checks).filter(Boolean).length;base.manglik={checks,severity:hits===0?'None':hits===1?'Low':hits===2?'Medium':'High',percentage:Math.round(hits/3*100)};const DASHAS=[{name:'Ketu',years:7,status:'Difficult',color:'#ef5b70'},{name:'Venus',years:20,status:'Good',color:'#36c98f'},{name:'Sun',years:6,status:'Neutral',color:'#f5b942'},{name:'Moon',years:10,status:'Good',color:'#36c98f'},{name:'Mars',years:7,status:'Difficult',color:'#ef5b70'},{name:'Rahu',years:18,status:'Difficult',color:'#ef5b70'},{name:'Jupiter',years:16,status:'Good',color:'#36c98f'},{name:'Saturn',years:19,status:'Challenging',color:'#f5b942'},{name:'Mercury',years:17,status:'Good',color:'#36c98f'}];const nakIndex=Math.floor(moon.longitude/(360/27)),fraction=(moon.longitude%(360/27))/(360/27),startDashaIndex=nakIndex%9;let ageYears=(Date.now()-date.getTime())/(365.25*24*60*60*1000);if(ageYears<0)ageYears=0;let elap=0,di=startDashaIndex,dashaRes=null;const bal=(1-fraction)*DASHAS[startDashaIndex].years;if(ageYears<=bal){dashaRes={name:DASHAS[startDashaIndex].name,status:DASHAS[startDashaIndex].status,color:DASHAS[startDashaIndex].color,completedPercent:Math.min(100,Math.round((ageYears/DASHAS[startDashaIndex].years)*100)),remainingYears:+bal.toFixed(1)}}else{elap+=bal;di=(di+1)%9;while(elap<120){const nd=DASHAS[di];if(ageYears<=elap+nd.years){const act=ageYears-elap;dashaRes={name:nd.name,status:nd.status,color:nd.color,completedPercent:Math.min(100,Math.round((act/nd.years)*100)),remainingYears:+(nd.years-act).toFixed(1)};break}elap+=nd.years;di=(di+1)%9}}base.mahadasha=dashaRes||{name:'Mercury',status:'Good',color:'#36c98f',completedPercent:100,remainingYears:0};return base}
function panchang(input){const date=new Date(input.date),sun=sidereal('Sun',date),moon=sidereal('Moon',date),phase=norm(moon-sun),tithi=Math.floor(phase/12)+1,yoga=Math.floor(norm(sun+moon)/(360/27))+1,karana=Math.floor(phase/6)+1,nakIndex=Math.floor(moon/(360/27));let sunrise=null,sunset=null;if(Number.isFinite(+input.lat)&&Number.isFinite(+input.lon)){const obs=new Astronomy.Observer(+input.lat,+input.lon,0),rise=Astronomy.SearchRiseSet(Astronomy.Body.Sun,obs,+1,date,1),set=Astronomy.SearchRiseSet(Astronomy.Body.Sun,obs,-1,date,1);sunrise=rise?.date?.toISOString()||null;sunset=set?.date?.toISOString()||null}return {date:date.toISOString(),tithi:{number:tithi,paksha:tithi<=15?'Shukla':'Krishna'},nakshatra:NAK[nakIndex],yoga,karana,sunrise,sunset,moonSign:SIGNS[Math.floor(moon/30)],ayanamsa:'Lahiri (approximation)'}}
module.exports={kundali,panchang,chart,SIGNS,NAK};
